"""Mouse cursor renderer for the editor preview.

Export-time cursor and click effects are generated by FFmpeg filtergraphs.
This module is intentionally Qt-only so opening the editor never imports
OpenCV-era rendering dependencies.
"""

import logging
import math
import os
from functools import lru_cache
from typing import List, Optional, Tuple

from .models import (
    MousePosition,
    ClickEvent,
    ClickEffectPreset,
    DEFAULT_CLICK_EFFECT,
    DEFAULT_CURSOR_SCALE,
    normalize_cursor_scale,
    VideoSpaceTransform,
)
from .cursor_registry import (
    cursor_asset_scale as registry_cursor_asset_scale,
    cursor_hotspot as registry_cursor_hotspot,
    cursor_svg_path,
    ensure_cursor_asset,
    get_cursor_preset,
)
from .cursor_animation import cursor_click_scale_at

logger = logging.getLogger(__name__)


# ── Cursor appearance ───────────────────────────────────────────────

CURSOR_COLOR = (255, 255, 255)       # white  (RGB for QPainter, BGR for CV)
CURSOR_OUTLINE = (30, 30, 30)        # near-black outline (softer than pure black)
CURSOR_OUTLINE_W = 2.0               # outline width
CURSOR_SHADOW_ALPHA = 80             # drop shadow opacity (0-255)

# ── Click effect appearance ─────────────────────────────────────────

CLICK_DURATION_MS = 400.0            # how long the click ripple is visible
CLICK_COLOR = (138, 92, 246)         # purple (#8b5cf6) in RGB
CLICK_MAX_RADIUS = 24.0              # max ripple radius (preview, scaled)


@lru_cache(maxsize=8)
def _load_cursor_asset(path: str, modified_ns: int):
    """Load and validate a custom cursor bitmap for the Qt preview."""
    _ = modified_ns
    from PySide6.QtGui import QImage

    image = QImage(path)
    return image if not image.isNull() else None


def _cursor_asset_image(path: str):
    if not path or not os.path.isfile(path):
        return None
    try:
        return _load_cursor_asset(path, os.stat(path).st_mtime_ns)
    except OSError:
        return None


def _interp_mouse(track: List[MousePosition], time_ms: float) -> Optional[Tuple[float, float]]:
    """Interpolate mouse position at *time_ms* from recorded track.

    Returns (x, y) in absolute screen coordinates, or None if no data.
    """
    if not track:
        return None
    if time_ms <= track[0].timestamp:
        return track[0].x, track[0].y
    if time_ms >= track[-1].timestamp:
        return track[-1].x, track[-1].y

    # Binary search for the right interval
    lo, hi = 0, len(track) - 1
    while lo < hi - 1:
        mid = (lo + hi) // 2
        if track[mid].timestamp <= time_ms:
            lo = mid
        else:
            hi = mid

    a, b = track[lo], track[hi]
    if b.resume_boundary and time_ms < b.timestamp:
        return a.x, a.y
    dt = b.timestamp - a.timestamp
    if dt <= 0:
        return a.x, a.y
    t = (time_ms - a.timestamp) / dt
    return a.x + (b.x - a.x) * t, a.y + (b.y - a.y) * t


# ── QPainter-based cursor/click effects (for editor preview) ────────


def _screen_point(
    x: float,
    y: float,
    mon_left: float,
    mon_top: float,
    mon_w: float,
    mon_h: float,
    screen_x: float,
    screen_y: float,
    screen_w: float,
    screen_h: float,
    video_transform: VideoSpaceTransform | None = None,
) -> Optional[Tuple[float, float]]:
    """Map an absolute monitor coordinate into the composed screen rect."""
    rel_x = (x - mon_left) / max(mon_w, 1.0)
    rel_y = (y - mon_top) / max(mon_h, 1.0)
    if not VideoSpaceTransform.contains_source_point(rel_x, rel_y):
        return None
    if video_transform is not None:
        rel_x, rel_y = video_transform.map_point(rel_x, rel_y)
    px = screen_x + rel_x * screen_w
    py = screen_y + rel_y * screen_h
    return px, py


def _monitor_bounds(monitor_rect: dict) -> Tuple[float, float, float, float]:
    """Return monitor bounds from project JSON, accepting common key names."""
    left = float(monitor_rect.get("left", monitor_rect.get("x", 0.0)))
    top = float(monitor_rect.get("top", monitor_rect.get("y", 0.0)))
    width = float(monitor_rect.get("width", monitor_rect.get("w", 1.0)))
    height = float(monitor_rect.get("height", monitor_rect.get("h", 1.0)))
    return left, top, max(width, 1.0), max(height, 1.0)


def draw_cursor_qpainter(
    painter,
    track: List[MousePosition],
    time_ms: float,
    monitor_rect: dict,
    screen_x: float,
    screen_y: float,
    screen_w: float,
    screen_h: float,
    video_transform: VideoSpaceTransform | None = None,
    cursor_asset_path: str = "",
    cursor_style_id: str = "arrow",
    cursor_hotspot: tuple[float, float] | None = None,
    cursor_scale: float = DEFAULT_CURSOR_SCALE,
    click_events: Optional[List[ClickEvent]] = None,
) -> None:
    """Draw the recorded cursor in the editor preview using QPainter."""
    pos = _interp_mouse(track, time_ms)
    if pos is None:
        return

    from PySide6.QtCore import QPointF, QRectF, Qt
    from PySide6.QtGui import QColor, QPainterPath, QPen, QBrush
    from PySide6.QtSvg import QSvgRenderer

    mon_left, mon_top, mon_w, mon_h = _monitor_bounds(monitor_rect)
    point_xy = _screen_point(
        pos[0], pos[1], mon_left, mon_top, mon_w, mon_h,
        screen_x, screen_y, screen_w, screen_h, video_transform,
    )
    if point_xy is None:
        return
    px, py = point_xy

    user_scale = normalize_cursor_scale(cursor_scale)
    base_size = max(20.0, min(96.0, screen_h * 0.035 * user_scale))
    click_scale = cursor_click_scale_at(time_ms, track, click_events or [])
    size = base_size * click_scale

    # Render packaged SVG cursors directly into the target painter rectangle.
    # This avoids creating a default-size raster and then enlarging it.
    effective_style_id = "arrow" if cursor_style_id == "custom" else cursor_style_id
    svg_path = cursor_asset_path if str(cursor_asset_path).lower().endswith(".svg") else ""
    if not svg_path:
        candidate = cursor_svg_path(effective_style_id)
        if candidate and os.path.isfile(candidate):
            svg_path = candidate
    if svg_path and os.path.isfile(svg_path):
        renderer = QSvgRenderer(svg_path)
        if renderer.isValid():
            default_size = renderer.defaultSize()
            source_w = max(default_size.width(), 1)
            source_h = max(default_size.height(), 1)
            draw_h = float(size)
            draw_w = draw_h * source_w / source_h
            if cursor_hotspot is not None:
                base_hotspot = cursor_hotspot
            elif cursor_asset_path:
                base_hotspot = (0.0, 0.0)
            else:
                base_hotspot = registry_cursor_hotspot(effective_style_id)
            hotspot_scale = draw_h / source_h
            painter.save()
            painter.setRenderHint(painter.RenderHint.Antialiasing, True)
            painter.setRenderHint(painter.RenderHint.SmoothPixmapTransform, True)
            renderer.render(
                painter,
                QRectF(
                    px - float(base_hotspot[0]) * hotspot_scale,
                    py - float(base_hotspot[1]) * hotspot_scale,
                    draw_w,
                    draw_h,
                ),
            )
            painter.restore()
            return

    custom_cursor = _cursor_asset_image(cursor_asset_path)
    hotspot_x, hotspot_y = (0, 0)
    if custom_cursor is None:
        try:
            builtin_path = ensure_cursor_asset(effective_style_id)
            custom_cursor = _cursor_asset_image(builtin_path)
            hotspot_x, hotspot_y = registry_cursor_hotspot(effective_style_id)
            builtin_scale = registry_cursor_asset_scale(effective_style_id)
            hotspot_x *= builtin_scale
            hotspot_y *= builtin_scale
        except Exception:
            logger.warning("Could not load cursor preset %s", cursor_style_id, exc_info=True)
    if custom_cursor is not None:
        if cursor_hotspot is not None:
            hotspot_x, hotspot_y = cursor_hotspot
        scale = size / max(float(custom_cursor.height()), 1.0)
        draw_w = max(1.0, float(custom_cursor.width()) * scale)
        painter.save()
        painter.setRenderHint(painter.RenderHint.SmoothPixmapTransform, True)
        painter.drawImage(
            QRectF(px - hotspot_x * scale, py - hotspot_y * scale, draw_w, size),
            custom_cursor,
        )
        painter.restore()
        return

    # Safe fallback: standard Windows-style arrow with a contrasting outline.
    scale = size / 20.0
    points = [
        QPointF(px, py),
        QPointF(px, py + 17 * scale),
        QPointF(px + 4 * scale, py + 13 * scale),
        QPointF(px + 7 * scale, py + 20 * scale),
        QPointF(px + 9 * scale, py + 19 * scale),
        QPointF(px + 6 * scale, py + 12 * scale),
        QPointF(px + 12 * scale, py + 12 * scale),
    ]

    path = QPainterPath(points[0])
    for point in points[1:]:
        path.lineTo(point)
    path.closeSubpath()

    painter.save()
    painter.setRenderHint(painter.RenderHint.Antialiasing, True)
    painter.setPen(Qt.PenStyle.NoPen)
    painter.setBrush(QBrush(QColor(0, 0, 0, CURSOR_SHADOW_ALPHA)))
    painter.translate(1.8 * scale, 2.2 * scale)
    painter.drawPath(path)
    painter.translate(-1.8 * scale, -2.2 * scale)
    painter.setPen(QPen(QColor(*CURSOR_OUTLINE), max(CURSOR_OUTLINE_W * scale, 1.0)))
    painter.setBrush(QBrush(QColor(*CURSOR_COLOR)))
    painter.drawPath(path)
    painter.restore()


def draw_clicks_qpainter(
    painter,
    click_events: List[ClickEvent],
    time_ms: float,
    monitor_rect: dict,
    screen_x: float,
    screen_y: float,
    screen_w: float,
    screen_h: float,
    preset: Optional[ClickEffectPreset] = None,
    video_transform: VideoSpaceTransform | None = None,
) -> None:
    """Draw click effects in the editor preview using QPainter."""
    if not click_events:
        return
    if preset is None:
        preset = DEFAULT_CLICK_EFFECT
    if preset.color[3] == 0 or preset.duration_ms <= 0:
        return

    from PySide6.QtCore import QPointF, Qt
    from PySide6.QtGui import QColor, QPen, QBrush

    mon_left, mon_top, mon_w, mon_h = _monitor_bounds(monitor_rect)
    base_color = QColor(*preset.color)
    style = preset.style if preset.style in ("ripple", "burst", "highlight") else "ripple"
    max_r = max(float(preset.radius), screen_h * 0.025)
    window_start = time_ms - preset.duration_ms

    painter.save()
    painter.setRenderHint(painter.RenderHint.Antialiasing, True)
    for click in click_events:
        if click.timestamp < window_start or click.timestamp > time_ms:
            continue
        age = time_ms - click.timestamp
        if age < 0 or age > preset.duration_ms:
            continue
        t = age / preset.duration_ms
        point_xy = _screen_point(
            click.x, click.y, mon_left, mon_top, mon_w, mon_h,
            screen_x, screen_y, screen_w, screen_h, video_transform,
        )
        if point_xy is None:
            continue
        px, py = point_xy
        point = QPointF(px, py)

        if style == "burst":
            alpha = int(base_color.alpha() * (1.0 - t))
            if alpha <= 8:
                continue
            color = QColor(base_color)
            color.setAlpha(alpha)
            painter.setPen(QPen(color, max(1.5, 3.0 * (1.0 - t)), Qt.PenStyle.SolidLine, Qt.PenCapStyle.RoundCap))
            inner_r = max_r * 0.22 * (1.0 + t)
            outer_r = max_r * (0.45 + 0.85 * t)
            for i in range(8):
                angle = 2.0 * math.pi * i / 8
                painter.drawLine(
                    QPointF(px + math.cos(angle) * inner_r, py + math.sin(angle) * inner_r),
                    QPointF(px + math.cos(angle) * outer_r, py + math.sin(angle) * outer_r),
                )
        elif style == "highlight":
            color = QColor(base_color)
            color.setAlpha(int(base_color.alpha() * 0.45 * (1.0 - t)))
            painter.setPen(Qt.PenStyle.NoPen)
            painter.setBrush(QBrush(color))
            painter.drawEllipse(point, max_r * 0.8, max_r * 0.8)
        else:
            ring = QColor(base_color)
            ring.setAlpha(int(base_color.alpha() * (1.0 - t)))
            radius = max_r * (0.3 + 0.7 * t)
            if ring.alpha() > 8:
                painter.setPen(QPen(ring, max(1.5, 3.0 * (1.0 - t))))
                painter.setBrush(Qt.BrushStyle.NoBrush)
                painter.drawEllipse(point, radius, radius)

            dot = QColor(base_color)
            dot.setAlpha(int(base_color.alpha() * max(0.0, 1.0 - t * 1.8)))
            if dot.alpha() > 8:
                painter.setPen(Qt.PenStyle.NoPen)
                painter.setBrush(QBrush(dot))
                painter.drawEllipse(point, max(2.5, 5.0 * (1.0 - t * 0.5)), max(2.5, 5.0 * (1.0 - t * 0.5)))
    painter.restore()
